### ISSUE TITLE
App plan

### ISSUE THREAD

**Issue by ianvdhSBM** [ianvdhSBM/500px-browser#1]
### Choose architecture

Options:
- React/Redux / Redux-auth
- React/Redux/Node with Passport

### General

- [x] set up eslint

### Server setup
  
- 4 routes?
  - [x] /
  - [x] /login
  - [x] get /photos
  - [ ] post /photo/:id/vote
- [x] configure OAuth
- [x] decide on how to store the user credentials

### Client setup

- [x] set up webpack config
- [x] Redux store
  - [ ] user account 
  - [x] details from OAuth
  - [x] photos
  - [ ] votes ?
- [ ] Actions
  - [x] login
  - [x] fetchPhotos
  - [x] likePhoto
  - [ ] dislikePhoto
- [x] design the thing!

---

# Challenge

## Overview

In this challenge we are asking for your help building a simple web application.  The work required includes both frontend and backend work. The web app will consume content from the 500px public API, use 500px’s OAuth login, and support user-specific social actions.

During the development of this web app, you may face different design or implementation choices.  You’re free to make any such choices as you see fit; however, please make sure you document these decisions and include them in your code as either comments or in a summary included with your submission.  We want to see how you think, what decisions you make, and why.

This challenge is designed for candidates to showcase their learning, problem solving, and programming skills. There is no strict time limit, but please let us know your estimation on how long this challenge will take.

## Rules and Tools

To build the web app, feel free to use any programming languages and associated frameworks you want.  If you’re not sure what to use, we’d suggest Ruby on Rails, as this is the framework we use at 500px.  Note: If you choose a different framework, we strongly suggest using one that follows the MVC pattern.

It’s okay to use some third-party libraries or plugins (e.g., gems, jQuery plugins), but we might ask you about reasons behind picking particular ones.

You must check your solution into Github and maintain a communicative commit history so that we can follow the evolution of your solution. Also, please put your documentation in Github wiki pages or a README.md

Please create separate branches (or apply tags) for your solution at the end of each of the tasks, so that we can see your solution for each task separately.
This challenge is not designed to be difficult, but the code you write should meet your own high standards. We value thoughtful, clean, concise and clear code.

## Assessment

Your solution will be assessed before an on-site interview. If you are invited for an interview, we’ll have some follow-up questions about why you designed and implemented your app the way you did, and ask questions about how your app might evolve in different situations. 

### Task 1 - Photo Showcase

Please write a simple web app to showcase the Top 100 Popular photos from 500px.  More specifically, the Top 100 Popular photos must be dynamically obtained from a 500px public API endpoint. Inside the web app, please use the MVC pattern as much as possible, since you will be asked to further extend this web app later.

In terms of UI, feel free to choose the frontend presentation of the photos, such as a grid or a list.  Pick the view you think is the best for a group of photos.

You can make use of the 500px API documentation to know how to interact with the 500px API. There is also a handy gem which helps simplify calling the 500px API, although you are free to use whichever method you prefer.

### Task 2 - 500px Interactions

The 500px API is a standard OAuth 1.0a provider.  Extend your web app to allow users to log into your application using their existing 500px credentials.  Your web app will work as a standard OAuth client and obtain an access token from 500px.com.

Once a valid token is obtained, you can use it to execute user-specific actions on 500px resources (i.e., photos presented in your web app).  For simplicity, you only need to support one of our social actions --- like --- in your web app.  Add a “like” button to each photo, which, when clicked, allows a logged-in user to like individual photos.

One straightforward way of implementing this is to use the OmniAuth gem, which handles most of the OAuth work for you. Specifically, you’ll want to use the 500px OmniAuth strategy gem, which provides an implementation of OmniAuth ready for use with 500px. Follow the instructions for the 500px OmniAuth strategy to setup the gem, and then have a look at the OmniAuth guide for integrating it into your application. In their example, they create a User model from the auth_hash which OmniAuth provides, but you can do whatever you like with the returned data. The provided auth_hash will contain credentials as well as some user info, such as their name, which you can store as you like for use in making calls to the 500px API.

Note: You are free to choose how you would like to store the obtained access token, as long as you provide a proper explanation of your choice of solution.

### Task 3 - Cosmetics and Testing

To further polish this web application, you may choose one of these additional tasks:
Beautify the UI using your CSS talent, such as styling and animations.
Increase the reliability of the application by adding extensive test coverage. 

This task is pretty open; feel free to pick the direction you want to go in (or even do both if you have extra cycles). Please take this opportunity to show us what are good at in addition to coding.
